site_name: PhD Documentation
site_description: Documentation for my PhD research
site_author: Joseph Holmes
site_url: https://mydomain.org/phddocs
copyright: Copyright © 2025 Joseph Holmes
theme:
  icon:
    logo: material/bookshelf
  favicon: assets/icons/double-helix-svgrepo-com.svg
  name: material
  palette:
    #Light mode palette 
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode
      primary: deep purple
      accent: indigo
  #Dark mode palette
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode
      primary: deep purple
      accent: indigo
  #features:
    #- navigation.footer

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com
    - icon: fontawesome/brands/github
      link: https://github.com/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      #linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - admonition
  - pymdownx.details